controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

websocket_start:
    path: /websocket/start
    controller: App\Controller\WebSocketController::startWebSocketServer